{{if .Values.anyscaleCliToken}}
apiVersion: v1
kind: Secret
metadata:
  name: anyscale-cli-token
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ANYSCALE_CLI_TOKEN: {{ .Values.anyscaleCliToken | b64enc }}
{{end}}
