{{- if and (not .Values.anyscaleCliToken) .Values.externalSecret.enabled .Values.externalSecret.secretKey .Values.externalSecret.clusterSecretStore }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: anyscale-cli-token
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .Values.externalSecret.secretKey }}
    secretKey: {{ .Values.externalSecret.targetSecretKey }}
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.clusterSecretStore }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: anyscale-cli-token
{{- end }}