apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # Since this is a global resource, we append the namespace to it to support
  # launching multiple cloud deployments into a single Kubernetes cluster (we
  # assume that clouds to not share namespaces).
  name: anyscale-operator-token-reviewer-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # Since this is a global resource, we append the namespace to it to support
  # launching multiple cloud deployments into a single Kubernetes cluster (we
  # assume that clouds to not share namespaces).
  name: anyscale-operator-token-reviewer-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: anyscale-operator
    namespace: {{ .Release.Namespace }}
