apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anyscale-operator
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: anyscale-operator
subjects:
- kind: ServiceAccount
  name: anyscale-operator
  namespace: {{ .Release.Namespace }}
